# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://scsastctrl.oxxo.fortifyhosted.com/scancentral-ctrl/'
    scanCentralClientToken: '6K1zdMJq9oQRpGIVU9GxZGhwtplc7s11shRUpf2djk4yZeex'
    sscUrl: 'https://ssc.oxxo.fortifyhosted.com/'
    sscCiToken: 'cf37185a-0807-4cf2-a546-2180c54db8e4'
    uploadToSSC: true
    applicationName: 'InsecureForum'
    applicationVersion: '1.0'
    buildFailureCriteria: '[fortify priority order]:critical'